## spammr: *S*patiotemporal *P*opulation *A*dmixture and *M*igration *M*odels in *R*

### ⚠️⚠️⚠️ WARNING ⚠️⚠️⚠️

**This software is still under heavy development!**

If you are interested in realistic spatio-temporal population genetic
simulations and somehow stumbled upon this repository then
congratulations! Your google-fu is strong.

This repository is public mostly so that I can share the results of my
work with collaborators without too much hassle. I have been making
good progress towards a first beta version, but the package still has
some way to go before being production ready.

That said, if you would like to learn more, or if you're feeling brave
and would like to test the package yourself, take a look at the
[tutorial](https://bodkan.net/spammr/articles/tutorial.html). Note
that getting it installed with all the geospatial dependencies can be
a little bit tricky at this point (see the relevant section in the
tutorial). If loading the package fails, check the error messages for
missing software and install it using the package manager of your
choice (on a Mac I recommend _homebrew_).

If you would like to stay updated with the developments:

1. Click on the "Watch" button on the project's [Github
website](https://www.github.com/bodkan/spammr).

2. Follow me on [Twitter](https://www.twitter.com/fleventy5). I might
post some updates once the software is a bit more ready.

