---
title: "A full example of a spatial population model"
author: "Martin Petr"
output: rmarkdown::html_vignette
vignette: >
 %\VignetteEncoding{UTF-8}
 %\VignetteIndexEntry{A full example of a spatial population model}
 %\VignetteEngine{knitr::rmarkdown}
---

```{r include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 7,
  fig.height = 5,
  dpi = 100
)

#devtools::install_github("bodkan/spammr")
#library(spammr)
devtools::load_all(".")
```

## Define the world context

```{r }
world <- world_map(
  xrange = c(-15, 60),  # min-max longitude
  yrange = c(20, 65),   # min-max latitude
  crs = "EPSG:3035"  # real projected CRS used internally
)
plot(world)
```

## Define some useful geographic regions

```{r }
africa <- region(
  "Africa", world,
  coords = list(
    c(-18, 20), c(40, 20), c(30, 33),
    c(20, 32), c(10, 35), c(-8, 35)
  )
)

europe_anatolia <-region(
  "Western Europe & Anatolia", world,
  coords = list(c(-10, 35), c(-5, 35), c(10, 38), c(20, 35), c(38, 35),
                c(40, 40), c(30, 45), c(20, 58), c(-5, 60), c(-15, 50))
)

europe <- region(
  "Western Europe", world,
  coords = list(c(-8, 35), c(-5, 36), c(10, 38), c(20, 35), c(25, 35),
                c(28, 45), c(20, 58), c(-5, 60), c(-15, 50))
)

anatolia <- region(
  "Anatolia", world,
  coords = list(c(28, 35), c(40, 35), c(42, 40),
                c(30, 43), c(27, 40), c(25, 38))
)
```

## Define population dynamics

```{r }
afr <- population(
  "AFR", parent = "ancestor", Ne = 1000,
  world = world, region = africa
)
plot(afr)
afr

ooa <- population(
  "OOA", parent = afr, time = 51000, Ne = 200,
  center = c(30, 30), radius = 300, remove = 27000
) %>% migrate(
  trajectory = list(c(40, 30), c(50, 30), c(60, 40), c(70, 40)),
  start = 50000,
  end = 40000,
  snapshots = 30
)
plot(ooa)
ooa

ehg <- population(
  "EHG", time = 28000, Ne = 400, parent = ooa,
  world,
  coords = list(
    c(26, 55), c(38, 53), c(48, 53), c(60, 53),
    c(60, 60), c(48, 63), c(38, 63), c(26, 60)
  ),
  remove = 6000
)
plot(ehg)
ehg

eur <- population(
  name = "EUR", time = 25000, Ne = 300, parent = ehg,
  world, region = europe
)
plot(eur)
eur

ana <- population(
  name = "ANA", time = 28000, Ne = 800, parent = ooa,
  world, center = c(34, 38), radius = 700,
  region = anatolia, remove = 6000
) %>% expand(
  by = 2500,
  start = 10000,
  end = 7000,
  snapshots = 10,
  region = europe_anatolia
)
plot(ana)
ana

yam <- population(
  name = "YAM", time = 7000, Ne = 600, parent = ehg,
  world, coords = list(
    c(26, 50), c(38, 49), c(48, 50),
    c(48, 56), c(38, 59), c(26, 56)
  ),
  remove = 2000
)
plot(yam)
yam

yam_migr <- population(
  name = "YAM_migr", time = 6000, Ne = 1000, parent = yam,
  world, coords = list(
    c(26, 50), c(38, 49), c(48, 50),
    c(48, 56), c(38, 59), c(26, 56)
  ),
  remove = 2900
) %>%
  migrate(
    trajectory = c(15, 50),
    start = 5000,
    end = 3000,
    snapshots = 8
  )
plot(yam_migr)
yam_migr
```

## Complete summary of spatial boundaries

```{r fig.width = 7, fig.height = 14}
plot(afr, ooa, ehg, eur, ana, yam, yam_migr, ncol = 2)
```

## Define admixture events

```{r }
admixtures <- list(
  admixture(from = ana, to = eur, rate = 0.5, start = 8500, end = 7000),
  admixture(from = yam_migr, to = eur, rate = 0.7, start = 4000, end = 3000)
)
```

## Compile the whole model and load it in SLiM

```{r }
compile(
  maps = list(afr, ooa, ehg, eur, ana, yam, yam_migr),
  admixtures = admixtures,
  output_dir = "/tmp/test-model/",
  overwrite = TRUE
)

```
```{r eval = FALSE}
run_slim(
  model_dir = "/tmp/test-model/",
  gen_time = 30, burnin = 200, sim_length = 70000,
  interaction = 30, spread = 20, seq_length = 100, recomb_rate = 0
)

```
```{r eval = FALSE}
animate(
  locations = "model/output_locations.tsv.gz",
  gif = "model/output_anim.gif",
  gen_time = 30,
  nframes = 200
)
```

