#' Convert spatio-temporal tree sequence data to a spatial format
#'
#' @param ts pyslim.SlimTreeSequence object
#' @param crs For spatial models, which coordinate reference system to reproject
#'   individual locations to? If \code{NULL} (default), coordinates are
#'   reprojected to the coordinate reference system (CRS) of the entire spatial
#'   model. Alternatively, a CRS code accepted by GDAL, a valid integer EPSG
#'   value, an object of class \code{crs}, can be specified to change the
#'   reprojection to a different CRS.
#'
#' @return Spatial object of the class \code{slendr_ts} and \code{sf}
#'
#' @export
ts_spatial <- function(ts, crs = NULL) {
  check_ts_class(ts)

  if (!has_map(model$populations[[1]]))
    stop("Cannot create a spatial object from tree sequence data generated by a non-spatial model.",
         call. = FALSE)

  model <- ts_model(ts)
  individuals <- ts_individuals(ts)
  nodes <- ts_nodes(ts)
  edges <- ts_edges(ts)

  # get all non-root nodes from the tree sequence
  child_nodes <- edges %>%
    dplyr::group_nest(child, .key = "parents") %>%
    dplyr::inner_join(nodes, by = c("child" = "id")) %>%
    dplyr::arrange(-time)

  # process table of individuals to get information about potential
  # ancestral locations and times (and notes in those individuals)
  ind_info <- individuals %>%
    dplyr::select(time, raster_x, raster_y, chr1_id, chr2_id) %>%
    tidyr::gather("node", "node_id", -c(time, raster_x, raster_y)) %>%
    dplyr::select(-node, anc_time = time, anc_raster_x = raster_x,
                  anc_raster_y = raster_y, anc_node_id = node_id)

  # iterate over all nodes from the oldest (those just behind some root)
  # and proceed "down" in the genealogy, remembering for each node
  # all ancestors above (dynamic programming style)
  ancestor_list <- vector(mode = "list", length = nrow(nodes))
  for (i in child_nodes$child) {
    # who are the parents of the current node?
    parents <- child_nodes[child_nodes$child == i, ]$parents[[1]]

    # who are all the ancestors of previous generations collected so far?
    parent_ancestors <- dplyr::bind_rows(ancestor_list[unique(parents$parent + 1)])

    # bind all previous ancestors with the current parents
    ancestor_list[[i + 1]] <- dplyr::bind_rows(parents, parent_ancestors) %>%
      dplyr::mutate(node_id = i)
  }
  ancestors <- dplyr::bind_rows(ancestor_list) %>%
    dplyr::select(node_id, anc_id = parent, left, right) %>%
    dplyr::inner_join(ind_info, by = c("anc_id" = "anc_node_id")) %>%
    dplyr::arrange(node_id, anc_id, left) %>%
    dplyr::group_nest(node_id, anc_id, anc_time, anc_raster_x, anc_raster_y, .key = "interval")

  # convert the table of all individuals into a long format (two rows
  # for each sampled individual -- i.e. for each chromosome)
  individuals_long <- individuals %>%
    tidyr::gather(key = "node", value = "node_id", c("chr1_id", "chr2_id"))

  # to each node in a sampled individual, add the infered ancestors up to the root
  # of each genealogy
  combined <- dplyr::inner_join(individuals_long, ancestors, by = "node_id") %>%
    dplyr::select(name, node_id, time, raster_x, raster_y, anc_id, anc_raster_x,
                  anc_raster_y, anc_time, anc_id, dplyr::everything())

  # reproject coordinates to the original crs
  if (has_crs(model$world)) {
    if (is.null(crs)) crs <- sf::st_crs(model$world)

    ind_locations <- reproject(
      from = "raster", to = crs, coords = combined, model = model,
      input_prefix = "raster_", output_prefix = ""
    ) %>% as.data.frame()

    combined <- reproject(
      from = "raster", to = crs, add = TRUE, coords = combined, model = model,
      input_prefix = "anc_raster_", output_prefix = "anc_"
    )
  } else {
    ind_locations <- dplyr::select(combined, x = raster_x, y = raster_y)
    combined <- dplyr::select(-raster_x, -raster_y)
  }

  sf_samples <- sf::st_as_sf(ind_locations, coords = c("x", "y"), crs = crs)

  sf_result <- sf::st_as_sf(combined, crs = crs, coords = c("anc_x", "anc_y")) %>%
    dplyr::mutate(location = sf_samples$geometry) %>%
    dplyr::select(name, node_id, time, anc_id, anc_time, anc_location = geometry,
                  dplyr::everything()) %>%
    dplyr::filter(remembered)

  attr(sf_result, "model") <- model

  sf_result
}

#' Plot locations of ancestors of given sample on a map
#'
#' @export
plot_ancestors <- function(x, individual, connect = TRUE) {
  anc_sf <- dplyr::filter(sf, name == individual)

  # switch geometry to the individual's location column
  ind_sf <- sf::st_set_geometry(anc_sf[1, ], "location")

  if (connect) {
    sf_line <- dplyr::group_by(anc_sf, name) %>% dplyr::summarise()
    migration_geom <- geom_sf(data = sf_line)
  } else
    migration_geom <- NULL

  ggplot() +
    geom_sf(data = attr(sf, "world"), fill = "lightgray", color = NA) +
    migration_geom +
    geom_sf(data = ind_sf) +
    geom_sf(data = anc_sf, aes(color = anc_time)) +
    coord_sf(expand = 0) +
    ggtitle(paste("Locations of the ancestors of", individual)) +
    theme_bw()
}
